
ws {
	"_events": { },
	"_eventsCount": 1,
		"readyState": 1,
			"protocol": "",
				"_binaryType": "nodebuffer",
					"_closeFrameReceived": false,
						"_closeFrameSent": false,
							"_closeMessage": "",
								"_closeTimer": null,
									"_closeCode": 1006,
										"_extensions": { },
	"_receiver": {
		"_writableState":
		{
			"objectMode": false,
				"highWaterMark": 16384,
					"finalCalled": false,
						"needDrain": false,
							"ending": false,
								"ended": false,
									"finished": false,
										"destroyed": false,
											"decodeStrings": true,
												"defaultEncoding": "utf8",
													"length": 0,
														"writing": false,
															"corked": 0,
																"sync": true,
																	"bufferProcessing": false,
																		"writecb": null,
																			"writelen": 0,
																				"bufferedRequest": null,
																					"lastBufferedRequest": null,
																						"pendingcb": 0,
																							"prefinished": false,
																								"errorEmitted": false,
																									"emitClose": true,
																										"autoDestroy": false,
																											"bufferedRequestCount": 0,
																												"corkedRequestsFree": { "next": null, "entry": null }
		},
		"writable": true,
			"_events": { },
		"_eventsCount": 6,
			"_binaryType": "nodebuffer",
				"_extensions": { },
		"_isServer": true,
			"_maxPayload": 104857600,
				"_bufferedBytes": 0,
					"_buffers": [],
						"_compressed": false,
							"_payloadLength": 0,
								"_fragmented": 0,
									"_masked": false,
										"_fin": false,
											"_opcode": 0,
												"_totalPayloadLength": 0,
													"_messageLength": 0,
														"_fragments": [],
															"_state": 0,
																"_loop": false
	}, "_sender": { "_extensions": { }, "_socket": { "connecting": false, "_hadError": false, "_handle": { "reading": true, "onconnection": null, "_consumed": true }, "_parent": null, "_host": null, "_readableState": { "objectMode": false, "highWaterMark": 16384, "buffer": { "head": null, "tail": null, "length": 0 }, "length": 0, "pipes": null, "pipesCount": 0, "flowing": true, "ended": false, "endEmitted": false, "reading": true, "sync": false, "needReadable": true, "emittedReadable": false, "readableListening": false, "resumeScheduled": true, "paused": false, "emitClose": false, "autoDestroy": false, "destroyed": false, "defaultEncoding": "utf8", "awaitDrain": 0, "readingMore": false, "decoder": null, "encoding": null }, "readable": true, "_events": { "end": [null, null] }, "_eventsCount": 5, "_writableState": { "objectMode": false, "highWaterMark": 16384, "finalCalled": false, "needDrain": false, "ending": false, "ended": false, "finished": false, "destroyed": false, "decodeStrings": false, "defaultEncoding": "utf8", "length": 0, "writing": false, "corked": 0, "sync": false, "bufferProcessing": false, "writecb": null, "writelen": 0, "bufferedRequest": null, "lastBufferedRequest": null, "pendingcb": 1, "prefinished": false, "errorEmitted": false, "emitClose": false, "autoDestroy": false, "bufferedRequestCount": 0, "corkedRequestsFree": { "next": null, "entry": null } }, "writable": true, "allowHalfOpen": true, "_sockname": null, "_pendingData": null, "_pendingEncoding": "", "server": { "_events": { }, "_eventsCount": 5, "_connections": 1, "_handle": { "reading": false, "onread": null }, "_usingWorkers": false, "_workers": [], "_unref": false, "allowHalfOpen": true, "pauseOnConnect": false, "httpAllowHalfOpen": false, "timeout": 120000, "keepAliveTimeout": 5000, "maxHeadersCount": null, "headersTimeout": 40000, "_connectionKey": "6::::8080" }, "_server": { "_events": { }, "_eventsCount": 5, "_connections": 1, "_handle": { "reading": false, "onread": null }, "_usingWorkers": false, "_workers": [], "_unref": false, "allowHalfOpen": true, "pauseOnConnect": false, "httpAllowHalfOpen": false, "timeout": 120000, "keepAliveTimeout": 5000, "maxHeadersCount": null, "headersTimeout": 40000, "_connectionKey": "6::::8080" }, "timeout": 0, "parser": null, "_paused": false }, "_firstFragment": true, "_compress": false, "_bufferedBytes": 0, "_deflating": false, "_queue": [] }, "_socket": { "connecting": false, "_hadError": false, "_handle": { "reading": true, "onconnection": null, "_consumed": true }, "_parent": null, "_host": null, "_readableState": { "objectMode": false, "highWaterMark": 16384, "buffer": { "head": null, "tail": null, "length": 0 }, "length": 0, "pipes": null, "pipesCount": 0, "flowing": true, "ended": false, "endEmitted": false, "reading": true, "sync": false, "needReadable": true, "emittedReadable": false, "readableListening": false, "resumeScheduled": true, "paused": false, "emitClose": false, "autoDestroy": false, "destroyed": false, "defaultEncoding": "utf8", "awaitDrain": 0, "readingMore": false, "decoder": null, "encoding": null }, "readable": true, "_events": { "end": [null, null] }, "_eventsCount": 5, "_writableState": { "objectMode": false, "highWaterMark": 16384, "finalCalled": false, "needDrain": false, "ending": false, "ended": false, "finished": false, "destroyed": false, "decodeStrings": false, "defaultEncoding": "utf8", "length": 0, "writing": false, "corked": 0, "sync": false, "bufferProcessing": false, "writecb": null, "writelen": 0, "bufferedRequest": null, "lastBufferedRequest": null, "pendingcb": 1, "prefinished": false, "errorEmitted": false, "emitClose": false, "autoDestroy": false, "bufferedRequestCount": 0, "corkedRequestsFree": { "next": null, "entry": null } }, "writable": true, "allowHalfOpen": true, "_sockname": null, "_pendingData": null, "_pendingEncoding": "", "server": { "_events": { }, "_eventsCount": 5, "_connections": 1, "_handle": { "reading": false, "onread": null }, "_usingWorkers": false, "_workers": [], "_unref": false, "allowHalfOpen": true, "pauseOnConnect": false, "httpAllowHalfOpen": false, "timeout": 120000, "keepAliveTimeout": 5000, "maxHeadersCount": null, "headersTimeout": 40000, "_connectionKey": "6::::8080" }, "_server": { "_events": { }, "_eventsCount": 5, "_connections": 1, "_handle": { "reading": false, "onread": null }, "_usingWorkers": false, "_workers": [], "_unref": false, "allowHalfOpen": true, "pauseOnConnect": false, "httpAllowHalfOpen": false, "timeout": 120000, "keepAliveTimeout": 5000, "maxHeadersCount": null, "headersTimeout": 40000, "_connectionKey": "6::::8080" }, "timeout": 0, "parser": null, "_paused": false },
	"_isServer": true
}

request {
	"_readableState":
	{
		"objectMode": false,
			"highWaterMark": 16384,
				"buffer": { "head": null, "tail": null, "length": 0 },
		"length": 0,
			"pipes": null,
				"pipesCount": 0,
					"flowing": null,
						"ended": true,
							"endEmitted": false,
								"reading": false,
									"sync": true,
										"needReadable": false,
											"emittedReadable": true,
												"readableListening": false,
													"resumeScheduled": false,
														"paused": true,
															"emitClose": true,
																"autoDestroy": false,
																	"destroyed": false,
																		"defaultEncoding": "utf8",
																			"awaitDrain": 0,
																				"readingMore": true,
																					"decoder": null,
																						"encoding": null
	},
	"readable": true,
		"_events": { },
	"_eventsCount": 1,
		"socket": {
		"connecting": false, "_hadError": false,
			"_handle": { "reading": true, "onconnection": null, "_consumed": true },
		"_parent": null,
			"_host": null,
				"_readableState": {
			"objectMode": false, "highWaterMark": 16384,
				"buffer": { "head": null, "tail": null, "length": 0 },
			"length": 0,
				"pipes": null,
					"pipesCount": 0,
						"flowing": true,
							"ended": false,
								"endEmitted": false,
									"reading": true,
										"sync": false,
											"needReadable": true,
												"emittedReadable": false,
													"readableListening": false,
														"resumeScheduled": true,
															"paused": false,
																"emitClose": false,
																	"autoDestroy": false,
																		"destroyed": false,
																			"defaultEncoding": "utf8",
																				"awaitDrain": 0,
																					"readingMore": false,
																						"decoder": null,
																							"encoding": null
		},
		"readable": true,
			"_events": { "end": [null, null] },
		"_eventsCount": 5,
			"_writableState": { "objectMode": false, "highWaterMark": 16384, "finalCalled": false, "needDrain": false, "ending": false, "ended": false, "finished": false, "destroyed": false, "decodeStrings": false, "defaultEncoding": "utf8", "length": 0, "writing": false, "corked": 0, "sync": false, "bufferProcessing": false, "writecb": null, "writelen": 0, "bufferedRequest": null, "lastBufferedRequest": null, "pendingcb": 1, "prefinished": false, "errorEmitted": false, "emitClose": false, "autoDestroy": false, "bufferedRequestCount": 0, "corkedRequestsFree": { "next": null, "entry": null } }, "writable": true, "allowHalfOpen": true, "_sockname": null, "_pendingData": null, "_pendingEncoding": "", "server": { "_events": { }, "_eventsCount": 5, "_connections": 1, "_handle": { "reading": false, "onread": null }, "_usingWorkers": false, "_workers": [], "_unref": false, "allowHalfOpen": true, "pauseOnConnect": false, "httpAllowHalfOpen": false, "timeout": 120000, "keepAliveTimeout": 5000, "maxHeadersCount": null, "headersTimeout": 40000, "_connectionKey": "6::::8080" }, "_server": { "_events": { }, "_eventsCount": 5, "_connections": 1, "_handle": { "reading": false, "onread": null }, "_usingWorkers": false, "_workers": [], "_unref": false, "allowHalfOpen": true, "pauseOnConnect": false, "httpAllowHalfOpen": false, "timeout": 120000, "keepAliveTimeout": 5000, "maxHeadersCount": null, "headersTimeout": 40000, "_connectionKey": "6::::8080" }, "timeout": 0, "parser": null, "_paused": false
	}, "connection": { "connecting": false, "_hadError": false, "_handle": { "reading": true, "onconnection": null, "_consumed": true }, "_parent": null, "_host": null, "_readableState": { "objectMode": false, "highWaterMark": 16384, "buffer": { "head": null, "tail": null, "length": 0 }, "length": 0, "pipes": null, "pipesCount": 0, "flowing": true, "ended": false, "endEmitted": false, "reading": true, "sync": false, "needReadable": true, "emittedReadable": false, "readableListening": false, "resumeScheduled": true, "paused": false, "emitClose": false, "autoDestroy": false, "destroyed": false, "defaultEncoding": "utf8", "awaitDrain": 0, "readingMore": false, "decoder": null, "encoding": null }, "readable": true, "_events": { "end": [null, null] }, "_eventsCount": 5, "_writableState": { "objectMode": false, "highWaterMark": 16384, "finalCalled": false, "needDrain": false, "ending": false, "ended": false, "finished": false, "destroyed": false, "decodeStrings": false, "defaultEncoding": "utf8", "length": 0, "writing": false, "corked": 0, "sync": false, "bufferProcessing": false, "writecb": null, "writelen": 0, "bufferedRequest": null, "lastBufferedRequest": null, "pendingcb": 1, "prefinished": false, "errorEmitted": false, "emitClose": false, "autoDestroy": false, "bufferedRequestCount": 0, "corkedRequestsFree": { "next": null, "entry": null } }, "writable": true, "allowHalfOpen": true, "_sockname": null, "_pendingData": null, "_pendingEncoding": "", "server": { "_events": { }, "_eventsCount": 5, "_connections": 1, "_handle": { "reading": false, "onread": null }, "_usingWorkers": false, "_workers": [], "_unref": false, "allowHalfOpen": true, "pauseOnConnect": false, "httpAllowHalfOpen": false, "timeout": 120000, "keepAliveTimeout": 5000, "maxHeadersCount": null, "headersTimeout": 40000, "_connectionKey": "6::::8080" }, "_server": { "_events": { }, "_eventsCount": 5, "_connections": 1, "_handle": { "reading": false, "onread": null }, "_usingWorkers": false, "_workers": [], "_unref": false, "allowHalfOpen": true, "pauseOnConnect": false, "httpAllowHalfOpen": false, "timeout": 120000, "keepAliveTimeout": 5000, "maxHeadersCount": null, "headersTimeout": 40000, "_connectionKey": "6::::8080" }, "timeout": 0, "parser": null, "_paused": false }, "httpVersionMajor": 1, "httpVersionMinor": 1, "httpVersion": "1.1", "complete": true, "headers": { "sec-websocket-version": "13", "sec-websocket-key": "R/p72Z2fL2FXCrdEWJcciA==", "connection": "Upgrade", "upgrade": "websocket", "sec-websocket-extensions": "permessage-deflate; client_max_window_bits", "host": "localhost:8080" }, "rawHeaders": ["Sec-WebSocket-Version", "13", "Sec-WebSocket-Key", "R/p72Z2fL2FXCrdEWJcciA==", "Connection", "Upgrade", "Upgrade", "websocket", "Sec-WebSocket-Extensions", "permessage-deflate; client_max_window_bits", "Host", "localhost:8080"], "trailers": { }, "rawTrailers": [], "aborted": false, "upgrade": true, "url": "/", "method": "GET", "statusCode": null, "statusMessage": null, "client": { "connecting": false, "_hadError": false, "_handle": { "reading": true, "onconnection": null, "_consumed": true }, "_parent": null, "_host": null, "_readableState": { "objectMode": false, "highWaterMark": 16384, "buffer": { "head": null, "tail": null, "length": 0 }, "length": 0, "pipes": null, "pipesCount": 0, "flowing": true, "ended": false, "endEmitted": false, "reading": true, "sync": false, "needReadable": true, "emittedReadable": false, "readableListening": false, "resumeScheduled": true, "paused": false, "emitClose": false, "autoDestroy": false, "destroyed": false, "defaultEncoding": "utf8", "awaitDrain": 0, "readingMore": false, "decoder": null, "encoding": null }, "readable": true, "_events": { "end": [null, null] }, "_eventsCount": 5, "_writableState": { "objectMode": false, "highWaterMark": 16384, "finalCalled": false, "needDrain": false, "ending": false, "ended": false, "finished": false, "destroyed": false, "decodeStrings": false, "defaultEncoding": "utf8", "length": 0, "writing": false, "corked": 0, "sync": false, "bufferProcessing": false, "writecb": null, "writelen": 0, "bufferedRequest": null, "lastBufferedRequest": null, "pendingcb": 1, "prefinished": false, "errorEmitted": false, "emitClose": false, "autoDestroy": false, "bufferedRequestCount": 0, "corkedRequestsFree": { "next": null, "entry": null } }, "writable": true, "allowHalfOpen": true, "_sockname": null, "_pendingData": null, "_pendingEncoding": "", "server": { "_events": { }, "_eventsCount": 5, "_connections": 1, "_handle": { "reading": false, "onread": null }, "_usingWorkers": false, "_workers": [], "_unref": false, "allowHalfOpen": true, "pauseOnConnect": false, "httpAllowHalfOpen": false, "timeout": 120000, "keepAliveTimeout": 5000, "maxHeadersCount": null, "headersTimeout": 40000, "_connectionKey": "6::::8080" }, "_server": { "_events": { }, "_eventsCount": 5, "_connections": 1, "_handle": { "reading": false, "onread": null }, "_usingWorkers": false, "_workers": [], "_unref": false, "allowHalfOpen": true, "pauseOnConnect": false, "httpAllowHalfOpen": false, "timeout": 120000, "keepAliveTimeout": 5000, "maxHeadersCount": null, "headersTimeout": 40000, "_connectionKey": "6::::8080" }, "timeout": 0, "parser": null, "_paused": false }, "_consuming": false, "_dumped": false, "parser": null
}

